# Board
BOARD_TITLE_MIN_LENGTH = 1
BOARD_TITLE_MAX_LENGTH = 100

# User
USER_NAME_MIN_LENGTH = 2
USER_NAME_MAX_LENGTH = 50
USER_NAME_PATTERN = r"^[a-zA-Z0-9а-яА-ЯёЁ\s_-]+$"  # буквы, цифры, пробелы, _, -

# Idea
IDEA_TITLE_MIN_LENGTH = 1
IDEA_TITLE_MAX_LENGTH = 150
IDEA_DESC_MAX_LENGTH = 2000
