#!/usr/bin/env python3
"""
Generate ZAP DAST scan summary report.

Usage:
    python scripts/generate_zap_summary.py
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


def load_zap_report(report_file: Path) -> Dict[str, Any]:
    if not report_file.exists():
        print(f"ZAP report not found: {report_file}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(report_file, encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"Invalid JSON: {e}", file=sys.stderr)
        sys.exit(1)


def analyze_alerts(data: Dict[str, Any]) -> tuple:
    alerts = data.get("site", [{}])[0].get("alerts", [])

    risk_counts = {"High": 0, "Medium": 0, "Low": 0, "Informational": 0}
    high_risks = []
    medium_risks = []

    for alert in alerts:
        risk_desc = alert.get("riskdesc", "")
        risk = risk_desc.split()[0] if risk_desc else "Unknown"

        if risk in risk_counts:
            risk_counts[risk] += 1

        alert_data = {
            "name": alert.get("name", "Unknown"),
            "risk": risk,
            "confidence": alert.get("confidence", "Unknown"),
            "description": alert.get("desc", "")[:200],
            "solution": alert.get("solution", "")[:200],
            "instances": len(alert.get("instances", [])),
        }

        if risk == "High":
            high_risks.append(alert_data)
        elif risk == "Medium":
            medium_risks.append(alert_data)

    return risk_counts, high_risks, medium_risks, len(alerts)


def generate_markdown_summary(
    target_url: str,
    risk_counts: Dict[str, int],
    high_risks: List[Dict],
    medium_risks: List[Dict],
    total_alerts: int,
) -> str:
    summary = f"""# DAST Scan Summary (ZAP Baseline)

**Scan Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}
**Target:** `{target_url}`

## Alert Summary

| Risk Level | Count |
|------------|-------|
| High | {risk_counts['High']} |
| Medium | {risk_counts['Medium']} |
| Low | {risk_counts['Low']} |
| Informational | {risk_counts['Informational']} |

**Total Alerts:** {total_alerts}

"""

    if high_risks:
        summary += "\n## High Risk Findings\n\n"
        for idx, alert in enumerate(high_risks, 1):
            summary += f"### {idx}. {alert['name']}\n\n"
            summary += f"**Confidence:** {alert['confidence']}\n"
            summary += f"**Instances:** {alert['instances']}\n"
            summary += f"**Description:** {alert['description']}\n\n"
            summary += f"**Solution:** {alert['solution']}\n\n"
            summary += "---\n\n"

    if medium_risks:
        summary += "\n## Medium Risk Findings\n\n"
        for idx, alert in enumerate(medium_risks[:5], 1):
            summary += f"### {idx}. {alert['name']}\n\n"
            summary += f"**Confidence:** {alert['confidence']}\n"
            summary += f"**Instances:** {alert['instances']}\n\n"

        if len(medium_risks) > 5:
            summary += f"*...and {len(medium_risks) - 5} more medium risk findings*\n\n"

    summary += """
## Next Steps

1. Review high and medium risk findings
2. Implement recommended solutions
3. Update `.zapignore` for accepted risks
4. Re-run scan to verify fixes

## Resources

- [ZAP Documentation](https://www.zaproxy.org/docs/)
- [OWASP Top 10](https://owasp.org/www-project-top-ten/)

---

*Generated by CI-DAST workflow*
"""

    return summary


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_zap_summary.py <reports_dir>", file=sys.stderr)
        sys.exit(1)

    reports_dir = Path(sys.argv[1])
    if not reports_dir.exists():
        print(f"Directory not found: {reports_dir}", file=sys.stderr)
        sys.exit(1)

    report_file = reports_dir / "zap_baseline.json"
    print(f"Loading ZAP report: {report_file}")

    data = load_zap_report(report_file)
    target_url = data.get("site", [{}])[0].get("@name", "http://localhost:8080")

    risk_counts, high_risks, medium_risks, total_alerts = analyze_alerts(data)

    print(f"\nAnalyzed {total_alerts} alerts:")
    print(f" High: {risk_counts['High']}")
    print(f" Medium: {risk_counts['Medium']}")
    print(f" Low: {risk_counts['Low']}")
    print(f" Informational: {risk_counts['Informational']}")

    summary = generate_markdown_summary(
        target_url, risk_counts, high_risks, medium_risks, total_alerts
    )

    summary_file = reports_dir / "zap_summary.md"
    with open(summary_file, "w", encoding="utf-8") as f:
        f.write(summary)

    print(f"\nSummary saved: {summary_file}")

    if risk_counts["High"] > 0:
        print(f"\nFound {risk_counts['High']} HIGH risk findings!")
        sys.exit(1)

    print("\nScan completed successfully")
    sys.exit(0)


if __name__ == "__main__":
    main()
